// File generated by FlutterFire CLI.
// Configure Firebase para uso com EMULADOR LOCAL
// O projectId PRECISA ser igual ao configurado em .firebaserc
// Para usar com projeto real no Firebase Console, execute:
//   flutterfire configure --project=SEU_PROJETO_ID

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configuração default - funciona com Firebase Local Emulator Suite
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Chaves dummy validas - funcionam APENAS com emulador local
  // Quando conectado aos emuladores (Auth 9099, Firestore 8080),
  // o Firebase nao valida essas chaves contra o servidor real.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUMMY-KEY-FOR-LOCAL-EMULATOR-ONLY',
    appId: '1:1234567890:android:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'whatsapp-clone-demo',
    storageBucket: 'whatsapp-clone-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUMMY-KEY-FOR-LOCAL-EMULATOR-ONLY',
    appId: '1:1234567890:ios:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'whatsapp-clone-demo',
    iosBundleId: 'com.example.whatsappClone',
    storageBucket: 'whatsapp-clone-demo.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUMMY-KEY-FOR-LOCAL-EMULATOR-ONLY',
    appId: '1:1234567890:macos:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'whatsapp-clone-demo',
    iosBundleId: 'com.example.whatsappClone',
    storageBucket: 'whatsapp-clone-demo.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUMMY-KEY-FOR-LOCAL-EMULATOR-ONLY',
    appId: '1:1234567890:web:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'whatsapp-clone-demo',
    storageBucket: 'whatsapp-clone-demo.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUMMY-KEY-FOR-LOCAL-EMULATOR-ONLY',
    appId: '1:1234567890:windows:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'whatsapp-clone-demo',
    storageBucket: 'whatsapp-clone-demo.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDUMMY-KEY-FOR-LOCAL-EMULATOR-ONLY',
    appId: '1:1234567890:linux:abcdef1234567890',
    messagingSenderId: '1234567890',
    projectId: 'whatsapp-clone-demo',
    storageBucket: 'whatsapp-clone-demo.appspot.com',
  );
}